### ISSUE TITLE
Launch failure

### ISSUE THREAD

**Issue by github-john-doe** [tombby11/Xamarin.Vlc#1]
[Mono] Assembly Ref addref Vlc.Forms.Droid[0xacc2f080] -> VlcXamarin[0xacc2f500]: 2
[art] JNI RegisterNativeMethods: attempt to register 0 native methods for md5ce87c198f9bfef9255447d7bebcfab2e.VlcPlayer
[VLC] Unable to load the anw library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/Vlc.Forms.Droid-1/base.apk"],nativeLibraryDirectories=[/data/app/Vlc.Forms.Droid-1/lib/x86, /data/app/Vlc.Forms.Droid-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libanw.21.so"
[VLC] Can't load vlcjni library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/Vlc.Forms.Droid-1/base.apk"],nativeLibraryDirectories=[/data/app/Vlc.Forms.Droid-1/lib/x86, /data/app/Vlc.Forms.Droid-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libvlcjni.so"
[art] System.exit called, status: 1
[AndroidRuntime] VM exiting with result code 1, cleanup skipped.

**Comment by NagaVenkateshParitala** [comment]
i am aslo getting same issues could u tell me how to solve this issues and please let me know and  it's urgent for me.Thanks a lots...

**Comment by NagaVenkateshParitala** [comment]
i am aslo getting same issues could u tell me how to solve this issues and please let me know and  it's urgent for me.Thanks a lots...
